#!/usr/bin/env bash
#The Bash script accepts one argument that is the password used to connect to the MySQL database
mysqldump -u root -p '$1' --all-database > backup.sql
tar -czvf "$(date +"%d-%m-%Y").tar.gz" backup.sql
